const actionType={
    TOGGLE_GROUP_BUTTON: 'TOGGLE_GROUP_BUTTON',
    SET_USER: 'SET_USER',
    LOADING: 'LOADING',
    LOG_OUT_USER: 'LOG_OUT_USER',
    ADD_BOOK: 'ADD_BOOK',
    MODIFY_BOOK: 'MODIFY_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
    RENT_BOOK: 'RENT_BOOK',
    GET_ALL_BOOKS: 'GET_ALL_BOOKS',
    GET_RENTED_BOOKS: 'GET_RENTED_BOOKS',
    GET_USER_PROFILE: 'GET_USER_PROFILE',
    GET_BORROWED_HISTORY: 'GET_BORROWED_HISTORY',
    SIGN_UP_USER: 'SIGN_UP_USER',
    LOGIN_USER: 'LOGIN_USER',
    AUTH_TOKEN: 'AUTH_TOKEN',
    GET_AVAILABLE_BOOKS: 'GET_AVAILABLE_BOOKS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
    CLOSE_SIDEBAR: 'CLOSE_SIDEBAR',
    SET_MESSAGE: 'SET_MESSAGE',
    RETURN_BOOK: "RETURN_BOOK",
    TOGGLE_SPINNER: 'TOGGLE_SPINNER'
    
}
export default actionType;